# Generated by Django 5.1.15 on 2026-07-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_phase7_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
