# Generated by Django 5.1.15 on 2026-07-24 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_phase1_auth_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("ABOUT", "About"),
                            ("INTERESTS", "Interests"),
                            ("ACTIVITY", "Activity"),
                            ("MEDIA", "Media"),
                            ("EXPERIENCE", "Experience"),
                            ("EDUCATION", "Education"),
                            ("PROJECTS", "Projects"),
                        ],
                        max_length=32,
                    ),
                ),
                ("content", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                db_index=True,
                default="PUBLIC",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["profile_visibility", "-updated_at"],
                name="profiles_pr_profile_9b1784_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["location"], name="profiles_pr_locatio_8c34ab_idx"
            ),
        ),
        migrations.AddField(
            model_name="profilesection",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="profiles.profile",
            ),
        ),
        migrations.AddIndex(
            model_name="profilesection",
            index=models.Index(
                fields=["profile", "order"], name="profiles_pr_profile_706468_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesection",
            constraint=models.UniqueConstraint(
                fields=("profile", "section_type"), name="unique_profile_section_type"
            ),
        ),
    ]
