# Generated by Django 5.1.15 on 2026-07-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profilesection_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="connection_visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("PRIVATE", "Private"),
                    ("CONNECTIONS_ONLY", "Connections only"),
                ],
                db_index=True,
                default="PUBLIC",
                help_text="Who can see this user's connections list.",
                max_length=32,
            ),
        ),
    ]
