# Generated by Django 5.1.15 on 2026-07-24 23:00

import apps.messaging.models
import apps.messaging.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[("DIRECT", "Direct"), ("GROUP", "Group")],
                        db_index=True,
                        default="DIRECT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "ordering": ["-last_message_at", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["-last_message_at"],
                        name="messaging_c_last_me_3f31f1_idx",
                    ),
                    models.Index(
                        fields=["-updated_at"], name="messaging_c_updated_666ea9_idx"
                    ),
                    models.Index(
                        fields=["conversation_type", "-last_message_at"],
                        name="messaging_c_convers_e56695_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(blank=True, max_length=5000)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("FILE", "File"),
                        ],
                        db_index=True,
                        default="TEXT",
                        max_length=16,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.messaging.models.message_attachment_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            apps.messaging.validators.validate_message_attachment,
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                        ],
                        db_index=True,
                        default="SENT",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="messaging.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("is_muted", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="messaging.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "conversation"],
                        name="messaging_c_user_id_0f11f9_idx",
                    ),
                    models.Index(
                        fields=["conversation", "last_read_at"],
                        name="messaging_c_convers_25851e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "user"),
                        name="unique_conversation_member",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="messaging_m_convers_516edb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="messaging_m_sender__9b0bb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_deleted", "-created_at"],
                name="messaging_m_convers_a6ddfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagestatus",
            index=models.Index(
                fields=["user", "status"], name="messaging_m_user_id_8082b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagestatus",
            index=models.Index(
                fields=["message", "status"], name="messaging_m_message_d3af7d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagestatus",
            constraint=models.UniqueConstraint(
                fields=("message", "user"), name="unique_message_status_per_user"
            ),
        ),
    ]
