# Generated by Django 5.1.15 on 2026-07-24 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacySetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        db_index=True,
                        default="PUBLIC",
                        max_length=16,
                    ),
                ),
                (
                    "post_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("CONNECTIONS_ONLY", "Connections only"),
                            ("PRIVATE", "Private"),
                        ],
                        default="PUBLIC",
                        max_length=32,
                    ),
                ),
                (
                    "connection_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("CONNECTIONS_ONLY", "Connections only"),
                            ("PRIVATE", "Private"),
                        ],
                        db_index=True,
                        default="PUBLIC",
                        max_length=32,
                    ),
                ),
                (
                    "message_permission",
                    models.CharField(
                        choices=[
                            ("CONNECTIONS_ONLY", "Connections only"),
                            ("NOBODY", "Nobody"),
                        ],
                        default="CONNECTIONS_ONLY",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "privacy setting",
                "verbose_name_plural": "privacy settings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
