# Generated by Django 5.1.15 on 2026-07-24 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="exports/%Y/%m/"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type_label",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("POST", "Post"),
                            ("COMMENT", "Comment"),
                            ("MESSAGE", "Message"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam"),
                            ("HARASSMENT", "Harassment"),
                            ("HATE_SPEECH", "Hate speech"),
                            ("VIOLENCE", "Violence"),
                            ("NUDITY", "Nudity"),
                            ("FAKE_ACCOUNT", "Fake account"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_type", models.CharField(db_index=True, max_length=32)),
                ("target_id", models.CharField(db_index=True, max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("WARNING", "Warning"),
                            ("CONTENT_REMOVED", "Content removed"),
                            ("USER_SUSPENDED", "User suspended"),
                            ("USER_BANNED", "User banned"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="moderation.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password change"),
                            ("PROFILE_UPDATE", "Profile update"),
                            ("MODERATION_ACTION", "Moderation action"),
                            ("ACCOUNT_DELETE", "Account delete"),
                            ("ACCOUNT_RESTORE", "Account restore"),
                            ("REPORT_CREATED", "Report created"),
                            ("BLOCK_USER", "Block user"),
                            ("UNBLOCK_USER", "Unblock user"),
                            ("DATA_EXPORT", "Data export"),
                            ("PRIVACY_UPDATE", "Privacy update"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=64)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="moderation__user_id_7bc7e1_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="moderation__action_39d2ef_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "blocked_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["blocker", "-created_at"],
                        name="moderation__blocker_8f2cde_idx",
                    ),
                    models.Index(
                        fields=["blocked_user", "-created_at"],
                        name="moderation__blocked_4eb2c0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked_user"), name="unique_block_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocker", models.F("blocked_user")), _negated=True
                        ),
                        name="block_no_self",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "-created_at"], name="moderation__status_282342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reporter", "-created_at"],
                name="moderation__reporte_350be5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["content_type_label", "object_id"],
                name="moderation__content_ec81c2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "UNDER_REVIEW"])),
                fields=("reporter", "content_type_label", "object_id", "reason"),
                name="unique_open_report",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="moderation__target__deb4a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["action", "-created_at"], name="moderation__action_9c4f47_idx"
            ),
        ),
    ]
