# Generated by Django 5.1.15 on 2026-07-24 22:47

import django.db.models.deletion
import django.db.models.functions.comparison
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("REMOVED", "Removed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["sender", "status"],
                        name="network_con_sender__e0f7d6_idx",
                    ),
                    models.Index(
                        fields=["receiver", "status"],
                        name="network_con_receive_43b0ca_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="network_con_status_763b0a_idx",
                    ),
                    models.Index(
                        fields=["sender", "receiver", "status"],
                        name="network_con_sender__556baa_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("receiver")), _negated=True
                        ),
                        name="connection_no_self",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.comparison.Least(
                            "sender", "receiver"
                        ),
                        django.db.models.functions.comparison.Greatest(
                            "sender", "receiver"
                        ),
                        condition=models.Q(
                            ("status__in", ["PENDING", "ACCEPTED", "BLOCKED"])
                        ),
                        name="unique_active_connection_pair",
                    ),
                ],
            },
        ),
    ]
