# Generated by Django 5.1.15 on 2026-07-24 20:10

import apps.media.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_phase2_posts_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.media.models.post_media_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "mp4",
                                    "webm",
                                    "mov",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video")], max_length=16
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.media.models.post_thumbnail_upload_to,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="READY",
                        max_length=16,
                    ),
                ),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "post media",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
