# Generated by Django 5.1.15 on 2026-07-24 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        ("posts", "0002_post_posts_post_created_dadbfe_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("HEART", "Heart")],
                        db_index=True,
                        default="HEART",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="comments.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "reaction_type"],
                        name="reactions_r_post_id_36c0cb_idx",
                    ),
                    models.Index(
                        fields=["comment", "reaction_type"],
                        name="reactions_r_comment_5aaee0_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="reactions_r_user_id_09910f_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("post__isnull", False), ("comment__isnull", True)
                            ),
                            models.Q(
                                ("post__isnull", True), ("comment__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="reaction_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("post__isnull", False)),
                        fields=("user", "post"),
                        name="unique_user_post_reaction",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("comment__isnull", False)),
                        fields=("user", "comment"),
                        name="unique_user_comment_reaction",
                    ),
                ],
            },
        ),
    ]
